project: 
  output-dir: docs
  type: website
  title: Appendix 0

website: 
  back-to-top-navigation: true
  navbar: 
    left: 
      - archive.qmd
    right: 
      - icon: github
        href: https://github.com/kiriushaMegabaitusha
        text: GitHub