project: 
  output-dir: docs
  type: website

website: 
  back-to-top-navigation: true
  navbar: 
    left: 
      - text: Archive / Архів
        href: archive.qmd
    right: 
      - icon: github
        href: https://github.com/kiriushaMegabaitusha
        text: GitHub